name: Daily Update
run-name: update of turbidity 🚀
on: workflow_dispatch
  #schedule:
 # - cron: "0 0 * * *"

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::lubridate
            any::cder
            any::sf
            github::https://github.com/InteragencyEcologicalProgram/deltamapr
            any::readxl

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("docs/index.Rmd")'
        
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: docs/index.Rmd
	        output_format: html
         
     - name: Commit results
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.Rmd
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

